#!/system/bin/sh
# auto zram activation init script with busybox search
# by show-p1984

echo "[90ZRAM]: Firing up /system/etc/init.d/90zram";

if [ ! -e /sys/block/zram0/disksize ] ; then
        echo "[90ZRAM]: ERROR unable to find /sys/block/zram0/disksize";
        echo "[90ZRAM]: Is this a ZRAM kernel?";
        echo "[90ZRAM]: ZRAM NOT ACTIVATED. (404)";
else
        #find busybox in /system
        bblocation=$(find /system/ -name 'busybox')
        if [ -n "$bblocation" ] && [ -e "$bblocation" ] ; then
                echo "[90ZRAM]: busybox found in:" $bblocation;
                echo "[90ZRAM]: Setting ZRAM disksize.";
                echo $((100*1024*1024)) > /sys/block/zram0/disksize

                echo "[90ZRAM]: Starting ZRAM...";
                bblocation=${bblocation%/*}
                cd $bblocation
                ./busybox mkswap /dev/block/zram0
                ./busybox swapon /dev/block/zram0

                echo "[90ZRAM]: ZRAM activated.";
        else
                echo "[90ZRAM]: ERROR! busybox not found!";
                echo "[90ZRAM]: Is busybox installed? Symlinks set?";
                echo "[90ZRAM]: ZRAM NOT ACTIVATED. (404)";
        fi
fi

